### ISSUE TITLE
Off topic: Is there a collection of pre made animated vector drawables somewhere?

### ISSUE THREAD

**Issue by AdityaAnand1** [tarek360/RichPath#1]
Take the following example included in the Readme itself.

![image](https://raw.githubusercontent.com/tarek360/RichPath/master/screenshots/ic_notifications.gif)

There's something about the motion, the way the bell moves and the clapper thingy follows. It looks natural, real. I as a developer could not have made this. This is the realm of designers.

And so for the most part, I am at the mercy of what I can Google up and I wonder how others make use of animated vector drawables in general. So I ask, does anyone know of a collection of animated vector drawable files? Something like [lottie files](https://www.lottiefiles.com/) perhaps. I reckon this would be immensely helpful to a lot of developers

**Comment by tarek360** [comment]
@AdityaAnand1 
It wasn't hard for me to implement this motion, just implement your motion logic on a big scale and set a long time to the animation to observe your motion easily,
then with few tunes, (increase values or decrease others), you will get it.
Anyway, I don't know a store or stock of the animated vector drawable but I hope if the community makes a one.
By the way, you can check this https://github.com/tarek360/Animated-Icons it's a small set of animated icons.
