### ISSUE TITLE
SVG just doing the outside border, completely filling holes

### ISSUE THREAD

**Issue by JonathanJumper** [tarek360/RichPath#11]
Hi I don't know how to ask this, I already made a question on the forum https://stackoverflow.com/questions/45900535/change-show-trim-path-on-svg

hoping you could help and show me some info about trim paths
Thanks

**Comment by tarek360** [comment]
Hi @JonathanJumper ,
I can't understand your question clearly, you want to animate the border like this?
![heart](https://user-images.githubusercontent.com/8615768/30245316-bc4df358-95d5-11e7-8ba6-af6d4f13cc1b.gif)

or what?

**Comment by tarek360** [comment]
Note in xml use android:fillColor to fill your path with the color or remove it if you don't. or/and use android:strokeColor to show the border and set a color to it

**Comment by tarek360** [comment]
@JonathanJumper check my comments https://stackoverflow.com/questions/45900535/change-show-trim-path-on-svg#comment79235388_45900535

**Comment by tarek360** [comment]
Hi @JonathanJumper

I will close the issue, but if you want a help in a specific anumation or a vector drawable please reopen it and notify me.

Thank you.
