### ISSUE TITLE
Fatal error on RichPathView#onMeasure()

### ISSUE THREAD

**Issue by duribreux** [tarek360/RichPath#12]
Woow. Doing few more tests after posting I solved my problem... ¯\_(ツ)_/¯

**Comment by MMagomedov** [comment]
Hi, can you explain how you fix this?

**Comment by duribreux** [comment]
@MMagomedov Sorry I don't remember this one. Was probably a setup mistake I had made.
Take a look at the [given sample](https://github.com/tarek360/RichPath/tree/develop/app/src/main/java/com/richpathanimator/sample) & compare with your implementation.

**Comment by MMagomedov** [comment]
@duribreux I fixed it. The problem was that it was necessary to set the app:vector parameter in the xml instead of android:src for the ImageView
