### ISSUE TITLE
some path do not show  sometime?

### ISSUE THREAD

**Issue by wysgh** [tarek360/RichPath#13]
`    <path
        android:pathData="m81 508 910 -24 6 254 -914 28 -2 -258z"
        android:strokeColor="#000"
        android:strokeLineCap="round"
        android:strokeLineJoin="round"
        android:strokeWidth="6" />`

**Comment by tarek360** [comment]
@wysgh please provide me with the whole XML file.

```xml
<vector
    xmlns:android="http://schemas.android.com/apk/res/android"
    ???????????
    ???????????
    ???????????
>

    <path
        android:pathData="m81 508 910 -24 6 254 -914 28 -2 -258z"
        android:strokeColor="#000"
        android:strokeLineCap="round"
        android:strokeLineJoin="round"
        android:strokeWidth="6"/>

</vector>
```

**Comment by wysgh** [comment]
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportHeight="1080"
    android:viewportWidth="1080">

**Comment by wysgh** [comment]
`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportHeight="1080"
    android:viewportWidth="1080">`

**Comment by tarek360** [comment]
@wysgh I have tested it and it works fine, please add more details about your issue.

**Comment by wysgh** [comment]
`  richPathView = (RichPathView) findViewById(R.id.richPathView);
        richPathView.setVectorDrawable(R.drawable.ic_day9);`

I use the same XMLfile,but it not work, My Phone is Nexus 7

**Comment by tarek360** [comment]
@wysgh I can't find any problem, I have tested it on Nexus 7 emulator and it works fine also, is that happen on other devices?

**Comment by tarek360** [comment]
Hi @wysgh

I will close the issue, but if you still have a problem please reopen it and notify me.

Thank you.
