### ISSUE TITLE
Hey, buddy, this library has holes in Android's version 18

### ISSUE THREAD

**Issue by wizong** [tarek360/RichPath#14]
prompt java.io.FileNotFoundException in install Android devices Will,

android.view.InflateException:Binary XML file line #42: Error inflating class com.richpath.RichPathView
 android.view.LayoutInflater.createView(LayoutInflater.java:683)

**Comment by tarek360** [comment]
@wizong 
is it happen consistently with Android API 18?

**Comment by tarek360** [comment]
Hi @wizong

I will close the issue, and if you still have a problem please notify me.

Thank you.
