### ISSUE TITLE
Animation does not work, after the change Drawable.

### ISSUE THREAD

**Issue by viyt** [tarek360/RichPath#15]
Hello Ahmed! Thank You for library! Good work!!!
I have a small problem. I need to programmatically replace drawable.
Drawable1 and Drawable2 different only in the attribute "android: fillColor".
For example
Drawable1:
`<path
        android:name="name"
        android:fillColor="#ffffff"
        android:pathData="M----z" />`
Drawable2:
`<path
        android:name="name"
        android:fillColor="#000000"
        android:pathData="M----z" />`

Drawable successfully replaced, but RichPathAnimator stops working.

**Comment by tarek360** [comment]
You can use the same draw and simply find the path then set it's fillColor as you want, if this isn't suitable for your case what's the code which you use to set the drawable and to animate it??

**Comment by viyt** [comment]
I did just that already. Thanks!
