### ISSUE TITLE
Editor. Render error

### ISSUE THREAD

**Issue by mgleonsc** [tarek360/RichPath#17]
Upgrade to Android Studio 2.3 and then the editor displays this error:
The following classes could not be instantiated:
- com.richpath.RichPathView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.

**Comment by tarek360** [comment]
Hi @mgleonsc why you closed it? :)

**Comment by mgleonsc** [comment]
Hola @tarek360 .
In my project I use other libraries, one of these was causing different components give this exception, remove it and the other worked well, so I closed the issue.
I still use RichPath is great...
Thanks for your attention.

**Comment by tarek360** [comment]
Thank you :)

**Comment by tarek360** [comment]
Thank you 👍
