### ISSUE TITLE
Vector size

### ISSUE THREAD

**Issue by mgleonsc** [tarek360/RichPath#2]
The vectors in some devices with higher density the size difference is very large.
![device-2017-07-18-174629](https://user-images.githubusercontent.com/30291468/28366852-733c2f6a-6c5c-11e7-8682-55eda4bf6743.png)
![device-2017-07-18-175339](https://user-images.githubusercontent.com/30291468/28366855-77ab411c-6c5c-11e7-8048-76de3a2e9637.png)

**Comment by mgleonsc** [comment]
the vector does not maintain the same ratio between different devices density

**Comment by tarek360** [comment]
Thank you for reporting this, I will check it.

**Comment by tarek360** [comment]
@mgleonsc fixed, please check [release 0.0.6](https://github.com/tarek360/RichPath/releases/tag/0.0.6) and close the issue if it's fixed with you.
Thanks.

**Comment by mgleonsc** [comment]
@tarek360  thanks for the time dedicated. RichPath is very good

**Comment by tarek360** [comment]
Hi @mgleonsc  This [version 0.0.7](https://github.com/tarek360/RichPath/releases/tag/0.0.7) give you more control on the `RichPathView` size and support padding, if you found any problem please inform me,
Thanks.

**Comment by mgleonsc** [comment]
@tarek360 Ok brother. Thanks again
