### ISSUE TITLE
Does not support Clip-Path?

### ISSUE THREAD

**Issue by YuganshT79** [tarek360/RichPath#25]
I have clipped my Vector in a circle clip-path and when I am using `ImageView` the vector is clipped and shown the way I want, but when using `RichPathVew` the clipping is gone.
Any idea why?

**Comment by tarek360** [comment]
Supporting Clip-Path is the next point on the TODO list in the [README](https://github.com/tarek360/RichPath/blob/master/README.md) file, I am a little bit busy these days but always all of the contributions are welcome.

**Comment by YuganshT79** [comment]
Ohhhh, sorry I didn't saw it!
You are doing a great job, take your time, I will try to contribute if I can

**Comment by tarek360** [comment]
You are welcome :)  thanks.
