### ISSUE TITLE
cannot solve dependency for this library. 

### ISSUE THREAD

**Issue by withleedh** [tarek360/RichPath#27]
As instruction, I pasted it. But couldn't build with the following statement.

implementation 'com.github.tarek360.RichPath:animator:0.1.0'

What's wrong with it?

**Comment by tarek360** [comment]
Have you added this to your root build.gradle file??(not your module build.gradle file)

```gradle
allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}
```

**Comment by withleedh** [comment]
It's works now :)
Thank you for your great response.
