### ISSUE TITLE
Release apk - Proguard - No animations?

### ISSUE THREAD

**Issue by entiti10** [tarek360/RichPath#3]
Hi!
First of all, thank you for your work. Excellent library.
I have one little problem when exporting a signed apk with proguard. When starting face love, animations are not happening.
If turn off the animation, the animations start to work again.
Any idea?
Thanks in advance

**Comment by tarek360** [comment]
Hi @entiti10 thank you for using RichPath :)

- Did the issue happen only with a signed APK and enabled Proguard?
- How you 'turn off' it ? do you mean` richPathAnimator.cancel();` ?

**Comment by entiti10** [comment]
Hi @tarek360 
Yes, I enable proguard and it not working

**Comment by tarek360** [comment]
Thank you @entiti10 for reporting this issue, it's fixed now https://github.com/tarek360/RichPath/releases/tag/0.0.8
check version 0.0.8 and please let me know if you have another issue.
Thank you.

**Comment by entiti10** [comment]
Thank you! 👍
