### ISSUE TITLE
Load Original SVG

### ISSUE THREAD

**Issue by tulaPivotal** [tarek360/RichPath#32]
Hello,
Can we load original svg in richpath view?
I have put svg in Raw folder and without convert it into vector drawable file want to load in richpath.
is this possible?
Looking forward to hearing from you.
Thanks

**Comment by tarek360** [comment]
Hi @tulaPivotal 
No you can **not** load SVGs directly, you need to covnert it to VectorDrawable XML file at first and like any drawable file you have to add it to  your drawable directory.

**Comment by tulaPivotal** [comment]
Hello,
Thanks for reply but while converting SVGs into VectorDrawable I couldn't find name of that path.
so is there any way to load SVGs with name?
Thanks

**Comment by tarek360** [comment]
You can add a name manually only for paths you want to control.

**Comment by tulaPivotal** [comment]
Hello,
I am loading SVG from URL so I can't add a name manually for path.
so what is other way to get a name for path?
Thanks

**Comment by tarek360** [comment]
So you can use RichPath, to use RichPath you need to add your drawable xml file to your res/drawable directory.
Please check the Readme file you will find some examples on how to use RichPath, also you can check the samples in the demo app.

**Comment by tulaPivotal** [comment]
yes, already I have checked. But I want to load SVG at runtime so how could I find richpath without any name?

**Comment by tarek360** [comment]
To know how it work with nested groups of paths please check the docs of `findRichPathByIndex()` from here
https://github.com/tarek360/RichPath/blob/master/richpath/src/main/java/com/richpath/RichPathView.java#L165
