### ISSUE TITLE
RichPath for iOS

### ISSUE THREAD

**Issue by sarojkumarojha** [tarek360/RichPath#42]
Hello Team ,

I found this is very productive library .
Is there any equivalent library is available for iOS(Objective-c / Swift 4)  ?

**Comment by tarek360** [comment]
Hi @sarojkumarojha 
Unfortunately, there is no RichPath for iOS
but I will be happy if you created one for iOS and if you want to understand how RichPath works internally let me know 👍 
Have a good day :)

**Comment by dvkch** [comment]
There is a library called [SVGKit](https://github.com/SVGKit/SVGKit) on iOS that has a lot of similar features, mainly loading an SVG file and rendering it, detecting selected path, and allowing modifying attributes on the fly
