### ISSUE TITLE
Detecting which group is clicked

### ISSUE THREAD

**Issue by serhiiskyrda** [tarek360/RichPath#70]
Hi Tarek

We are currently investigating the business case to get some metadata from group tag after clicking on specific area in SVG file. So there is nicely done pathClickListener (and there is only vector with paths but not groups).
What do u think about adding group field to RichPath class and store data about parental group there on xml parsing stage. 
And then inside onPathClickListener consumers can get the name of path's group. I can create pr for that, but first would like to know your opinion :)

Regards, Serhii

**Comment by serhiiskyrda** [comment]
Not relevant anymore.

**Comment by saraivaiabcd** [comment]
Have you implemented yet?

**Comment by serhiiskyrda** [comment]
> Have you implemented yet?

nope, we didn't. Decided to skip this feature at all.
