### ISSUE TITLE
Path is not properly  centered aligned inside RichPathView.

### ISSUE THREAD

**Issue by ashishkumawat** [tarek360/RichPath#9]
![sc](https://user-images.githubusercontent.com/9376615/29446154-4a3c6d6e-8408-11e7-98b3-e3f212e56db3.jpg)
For different width of RichPathView RichPath has different position some are slightly top some centered Vertically but as of requirement they have to be properly center vertical aligned so that they look like in single line. Hope you understand what i am trying to say.

**Comment by tarek360** [comment]
@ashishkumawat RichPathView scales the RichPath in aspect ratio so you shouldn't expect that the path width will change without the height. If you mean another thing please tell me.
